Terminology Design tools integration
essif-lab/framework pull request #177
Opened 2023-10-15 12:32 UTC by Ca5e

I've compared the changes in my fork to the master branch instead of the use-tev2 branch as I saw some work already being done on removing TEv1 documentation within the master branch.
Although deployment is done quite differently compared to before, I believe these changes should work with the current setup of the framework repository. My deployment (fork) can be seen here https://ca5e.github.io/framework/docs/essifLab.

2023-10-16 12:16 UTC, RieksJ requested changes
Changes seem ok.
What should be blocking for merge is that we do not yet have a HRG generated, so merging it to the eSSIF-Lab repo would mean that people browsing the site would no longer see a glossary. So we should wait until either we have a version of the glossary that we can use and publish from the repo, or there is an HRGT that would generate one.

2023-11-30 12:30 UTC, Ca5e commented
I've added the first version of the HRGT to my fork. Please have a look https://ca5e.github.io/framework/docs/essifLab-glossary. Merging should be possible.

2023-12-01 07:41 UTC, RieksJ approved these changes

2023-12-01 07:41 UTC, RieksJ commented on docs/glossary.md
I have modified the MRGRef tag spec to reflect that `converter="<converter>"` is optional. Of course, if it is omitted, that would imply that it be specified either on the command-line or in the configuration file (as is currently done). It gets rid of the 'ugly' `converter=""` text.

2023-12-01 07:41 UTC, RieksJ commented on docs/terms/identify.md
Please make sure that when texts are encountered that would not work, they somehow get logged with messages that help curators to fix the problem. (I cannot tell whether or not they currently are).

2023-12-01 14:03 UTC, Ca5e commented on docs/glossary.md
I think it may be useful to keep a simplified version as the default for using `essiflab` as the converter value.

So when using `{% hrg="" converter="essiflab" %}`.
We get:
```handlebars
### [{{glossaryTerm}}]({{navurl}})\n
{{glossaryText}}\n
```

Instead of the more complex converter that's actually used:
```handlebars
### [{{#if glossaryTerm}}{{glossaryTerm}}{{else}}{{capFirst term}}{{/if}}]({{localize navurl}})\n
{{#if glossaryText}}{{glossaryText}}{{else}}no `glossaryText` was specified for this entry.{{/if}}\n
```

This relates to writing the documentation for the HRGT and giving certain converter examples mainly. I suspect it might be more user friendly if we keep the essiflab default simple and explain the more complex one separately.

2023-12-04 06:56 UTC, RieksJ commented on docs/glossary.md
Ok to keep simple stuff in the tev2-specifications, but it may help them there to see examples from 'real life'.

2023-12-04 08:06 UTC, merged